### ISSUE TITLE
Splitting settings of datasets are different from GCN and GAT

### ISSUE THREAD

**Issue by yaokl-nju** [wokas36/DFNets#2]
Hi,

  I found that the number of training nodes w.r.t. Cora in your code (utils.py, line 178) is different from that in GCN and GAT, and the number is larger than that in GCN and GAT (200 > 140). I wonder whether the results in your paper is achieved with 200 training nodes? If yes, than the comparisons are meanless and unfair, better results can be achieved with more training nodes.

  Besides, what about the details of splitting settings w.r.t Citeseer and Pubmed? Can you please offer a complete version of codes for reproducing the results in the paper?

  I am very appreciate that if you can answer my question.

**Comment by wokas36** [comment]
Hi klyao,

We have performed an empirical evaluation for all models exclusively on the same data splitting of the all 4 datasets (Cora, Citesser, Pubmed, NELL) from [Yang et al. [2016]](https://arxiv.org/pdf/1603.08861.pdf). We decided to extend the amount of available data in order to avoid the bias-variance tradeoff to develop more powerful models. In my point of view, richer solutions can be exploited to better discriminate interesting local patterns if a sufficient amount of labelled samples can be provided from each classes. However, our models can also perform better when perturbation of the training samples. We replicate the results on Cora of GCN and GAT w.r.t the data splitting which we followed, but we observed there haven't much performance differences of GCN (81.7 +- 0.5) and GAT (83.3 +- 0.6). Sometimes, single split can be fragile and misleading the results with the same hyperparameter settings.

Hope that our reply can help you. Finally, thanks in advance for pointing out this issue to improve our results, and in the future, we can further extend our models by configuring hyperparameters fairly for all datasets with their standard splits.

**Comment by wokas36** [comment]
Hi klyao,

We've successfully configured our hyperparameter settings for the standard splits. Thanks again for pointing out this issue.

**Comment by yaokl-nju** [comment]
Another question: although you have the same training numbers (140 for cora) as Yang et al. [2016], but  the labeled nodes in Yang is balanced, where there have 20 nodes for each class. But in your codes, the training nodes are selected from the first 140, and I verify that it's unbalanced. 

Using the same settings as GCN and GAT do, or as APPNP do may be a good choice to make fair comparisons and avoid some difference and reproducing works.

Thank you very much for your patient reply!

**Comment by wokas36** [comment]
Hi klyao,

Thanks for pointing out this issue. I think it's due to the cora dataset version that we used, in our case first 140 samples are imbalanced. Please refer the [dfnet](https://github.com/wokas36/DFNets/tree/master/dfnet), here we use the same training samples as Yang et al. [2016] and now labeled nodes are balanced (20 nodes for each class).
